benefitsHub/posts/forms.py
"""
This module defines the post forms for the application.
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired


class MakePostForm(FlaskForm):
    """Class to create a new post"""
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    post_image = FileField('Upload picture', validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'])])
    submit = SubmitField('Post')

benefitsHub/benefits/routes.py
"""
This module defines the routes for the application.
"""
from flask import (render_template, url_for, flash, redirect,
                   request, Blueprint, abort)
from flask_login import current_user, login_required
from benefitsHub import db
from benefitsHub.models.base_model import Benefit, User
from benefitsHub.benefits.forms import BenefitForm
from benefitsHub.benefits.utils import save_picture
from markdown import markdown
from bleach.sanitizer import Cleaner
from bleach.linkifier import LinkifyFilter

cleaner = Cleaner(tags=['p', 'br', 'ul', 'ol', 'li', 'a'],
                  filters=[LinkifyFilter])

def linkify(text):
    return cleaner.clean(text)


# Create a Blueprint for benefits
benefits = Blueprint('benefits', __name__)


@benefits.route('/benefit/new', methods=["GET", "POST"])
@login_required
def new_benefit():
    """Flask route to create a new benefit"""
    form = BenefitForm()
    picture_file = None
    if form.validate_on_submit():
        # Save the benefit image if provided
        if form.benefit_image.data:
            picture_file = save_picture(form.benefit_image.data)
            benefit_image = picture_file

        # Apply linkify to description and requirement
        description_linkified = linkify(markdown(form.description.data, extensions=['extra']))
        sanitized_description = cleaner.clean(description_linkified)
        requirement_linkified = linkify(markdown(form.benefit_requirement.data, extensions=['extra']))
        sanitized_requirement = cleaner.clean(requirement_linkified)

        # Create a new Benefit object
        benefit = Benefit(name=form.name.data,
                          description=sanitized_description,
                          benefit_image=str(picture_file),
                          benefit_requirement=sanitized_requirement,
                          benefit_link=form.benefit_link.data,
                          benefit_start_date=form.benefit_start_date.data,
                          benefit_end_date=form.benefit_end_date.data,
                          benefit_status=form.benefit_status.data,
                          benefit_created_by=current_user.username,
                          user_id=current_user.id)
        # Add and commit the new benefit to the database
        db.session.add(benefit)
        db.session.commit()
        print(f"Image: {picture_file}")
        flash(f'Benefit {form.name.data} has been created!', 'success')
        return redirect(url_for('benefits.user_benefits',
                                username=current_user.username))
    # Generate URL for the benefit image
    image_file = url_for('static', filename='uploads/' + (picture_file if picture_file else 'default.jpeg'))
    return render_template('create_benefit.html', title='New Benefit',
                           image_file=image_file, form=form)


@benefits.route("/user_benefit/<string:username>")
def user_benefits(username):
    """View a user's posted benefits"""
    page = request.args.get('page', 1, type=int)
    # Get the user or return 404 if not found
    user = User.query.filter_by(username=username).first_or_404()
    # Query benefits for the user, ordered by creation date
    Benefit.query.filter_by(user=user)\
        .order_by(Benefit.benefit_created_on
                  .desc()).paginate(page=1)
    benefits = Benefit.query.filter_by(user=user)\
        .order_by(Benefit.benefit_created_on.desc())\
        .paginate(page=page, per_page=10)
    return render_template('user_benefits.html', title='user benefits',
                           benefits=benefits, user=user)


@benefits.route("/explore_benefits")
def explore_benefits():
    """Route to view all benefits"""
    page = request.args.get('page', 1,  type=int)
    # Query all benefits, ordered by creation date
    benefits = Benefit.query.order_by(Benefit.benefit_created_on.desc()).paginate(page=page, per_page=10)
    return render_template('explore_benefits.html',
                           benefits=benefits, title='Explore Benefits')


@benefits.route("/benefit/<int:benefit_id>")
def benefit(benefit_id):
    """View a single benefit by its id"""
    # Get the benefit or return 404 if not found
    benefit = Benefit.query.get_or_404(benefit_id)
    return render_template('benefit.html', title=f'benefit {benefit.id}',
                           benefit=benefit)


@benefits.route("/benefit/<int:benefit_id>/update", methods=["GET", "POST"])
@login_required
def update_benefit(benefit_id):
    """Updates a benefit"""
    # Get the benefit or return 404 if not found
    benefit = Benefit.query.get_or_404(benefit_id)
    # Check if the current user is the creator of the benefit
    if benefit.benefit_created_by != current_user.username:
        abort(403)
    form = BenefitForm()
    if form.validate_on_submit():
        # Update benefit fields with form data
        benefit.name = form.name.data
        if form.benefit_image.data:
            picture_file = save_picture(form.benefit_image.data)
            benefit.benefit_image = picture_file
        benefit.benefit_requirement = form.benefit_requirement.data
        benefit.description = form.description.data
        benefit.benefit_link = form.benefit_link.data
        benefit.benefit_start_date = form.benefit_start_date.data
        benefit.benefit_end_date = form.benefit_end_date.data
        benefit.benefit_created_by = form.benefit_created_by.data
        benefit.benefit_updated_on = form.benefit_updated_on.data
        # Commit changes to the database
        db.session.commit()
        flash('Your benefit has been updated!', 'success')
        return redirect(url_for('benefits.benefit', benefit_id=benefit.id))
    elif request.method == 'GET':
        # Populate form fields with existing benefit data
        form.name.data = benefit.name
        form.benefit_requirement.data = benefit.benefit_requirement
        form.description.data = benefit.description
        form.benefit_link.data = benefit.benefit_link
        form.benefit_start_date.data = benefit.benefit_start_date
        form.benefit_end_date.data = benefit.benefit_end_date
        form.benefit_created_by.data = benefit.benefit_created_by
        form.benefit_updated_on.data = benefit.benefit_updated_on
    return render_template('create_benefit.html', title='Update Benefit',
                           form=form, legend='Update Benefit')


@benefits.route("/benefit/<int:benefit_id>/delete", methods=["POST"])
@login_required
def delete_benefit(benefit_id):
    """Deletes a benefit"""
    # Get the benefit or return 404 if not found
    benefit = Benefit.query.get_or_404(benefit_id)
    # Check if the current user is the creator of the benefit
    if benefit.benefit_created_by != current_user.username:
        abort(403)
    # Delete the benefit from the database
    db.session.delete(benefit)
    db.session.commit()
    flash('Your benefit has been deleted!', 'success')
    return redirect(url_for('benefits.explore_benefit'))

benefitsHub/posts/routes.py
"""
This module contains the routes for the posts blueprint.
"""
from flask import (render_template, url_for, flash,
                   redirect, request, Blueprint, abort)
from flask_login import current_user, login_required
from benefitsHub import db
from benefitsHub.models.base_model import Post
from benefitsHub.posts.forms import MakePostForm
import os
from benefitsHub.posts.utils import save_picture


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=["GET", "POST"])
@login_required
def new_post():
    """Function to create a new post"""
    form = MakePostForm()
    picture_file = None
    if form.validate_on_submit():
        # Save the post image if provided
        if form.post_image.data:
            picture_file = save_picture(form.post_image.data)
            post_image = picture_file
        post = Post(title=form.title.data,
                    content=form.content.data,
                    author=current_user.username,
                    user_id=current_user.id,
                    post_image = picture_file)
        db.session.add(post)
        db.session.commit()
        flash(f'Post {form.title.data} has been created!', 'success')
        return redirect(url_for('posts.view_posts'))
    image_file = url_for('static', filename='post_uploads/' + (picture_file if picture_file else 'default.jpeg'))
    return render_template('create_post.html', title='New Post', form=form, image_file=image_file)


@posts.route("/view_posts", methods=['GET', 'POST'])
def view_posts():
    """Flask route to view posts made by users"""
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('view_posts.html', posts=posts, title='View Posts')


@posts.route("/post/<int:post_id>")
def post(post_id):
    """View a single post by its id"""
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=f'post {post.id}', post=post)


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    """Updates a post"""
    post = Post.query.get_or_404(post_id)
    if post.author != current_user.username:
        abort(403)
    form = MakePostForm()
    if form.validate_on_submit():
        if form.post_image.data:
            picture_file = save_picture(form.post_image.data)
            post.post_image = picture_file
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.post_image.data = post.post_image
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html',
                           title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    """Deletes a post"""
    post = Post.query.get_or_404(post_id)
    if post.author != current_user.username:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('posts.view_post'))

benefitsHub/users/routes.py
"""Routes for the users module"""
from flask import (render_template, url_for, flash, redirect, request,
                   Blueprint)
from benefitsHub import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from benefitsHub.models.base_model import User, Post
from benefitsHub.users.forms import (RegistrationForm, LoginForm,
                                     UpdateAccountForm, RequestResetForm,
                                     ResetPasswordForm)
from benefitsHub.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    """
    Route to register a new user.
    
    GET: Displays the registration form.
    POST: Processes the form submission, creates a new user, and redirects to login.
    """
    form = RegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)\
            .decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Welcome {user.username}!\
              Your account has been created successfully!\
              You can now login to see all your benefits.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    """
    Route to log in a user.
    
    GET: Displays the login form.
    POST: Authenticates the user and redirects to home or next page.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else\
                redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password',
                  'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    """Route to log out the current user."""
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=["GET", "POST"])
@login_required  # login is required to access this route.
def account():
    """
    Route to update the user's account information.
    
    GET: Displays the account update form.
    POST: Processes the form submission and updates the user's information.
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.update_picture.data:
            picture_file = save_picture(form.update_picture.data)
            current_user.profile_pic = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_pic = url_for('static', filename='assets/'
                          + current_user.profile_pic)
    return render_template('account.html', title='Account',
                           profile_pic=profile_pic, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    """
    Route to view a specific user's posts.
    
    Displays paginated posts for the given username.
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user.username)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=["GET", "POST"])
def reset_request():
    """
    Route to request a password reset.
    
    GET: Displays the password reset request form.
    POST: Processes the form and sends a reset email if valid.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with your password reset token. "
              "Use within 30 minutes.", 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password',
                           form=form)


@users.route('/reset_password/<token>', methods=["GET", "POST"])
def reset_token(token):
    """
    Route to reset password using a token.
    
    GET: Displays the password reset form.
    POST: Processes the form and updates the user's password if valid.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash("That is an invalid or expired token", 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)\
            .decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Welcome {user.username}!\
              Your password has been updated successfully!\
              You can now login to see all your benefits.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password',
                           form=form)

benefitsHub/templates/benefit.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2 anchor-tag" href="{{ url_for('benefits.user_benefits', username=benefit.benefit_created_by) }}">Posted By {{ benefit.benefit_created_by }}</a>
        On <small class="text-muted">{{ benefit.benefit_created_on.strftime('%Y-%m-%d') }}</small>
      </div>
        <h2 class="article-title">{{ benefit.name }}</h2>
	<h3>Description</h3>
	<div class="benefit-description text-start">
	   {{ benefit.description | nl2br | safe }}
	</div>
      <div class="mb-3">
	 <img class="benefit-img" src="{{ url_for('static', filename= 'uploads/' + benefit.benefit_image) }}" alt="Image of benefit">
      <h3>Requirement</h3>
      <div class="benefit-requirement text-start">
        {{ benefit.benefit_requirement | nl2br | safe }}
      </div>
      </div>
      {% if benefit.benefit_created_by == current_user.username %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('benefits.update_benefit', benefit_id=benefit.id) }}">Update</a>
          <button class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
      {% else %}
        <button data-link="{{ benefit.benefit_link }}" class="btn btn-primary apply-button">Apply</button>
      {% endif %}
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Benefit?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('benefits.delete_benefit', benefit_id=benefit.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

benefitsHub/templates/explore_benefits.html
{% extends "layout.html" %}
{% block content %}
    <h1>Explore All Benefits</h1>
    <div class="row">
        {% for benefit in benefits.items %}
            <div class="col-12 col-md-6 mb-4 media content-section">
                <div class="media-body">
                    <h2><a href="{{ url_for('benefits.benefit', benefit_id=benefit.id) }}">{{ benefit.name }}</a></h2>
                    <div class="media">
			{% if benefit.benefit_image %}
    				<img class="img-fluid benefit-img" src="{{ url_for('static', filename='uploads/' + benefit.benefit_image) }}" alt="Image of benefit">
			{% else %}
    				<img class="img-fluid benefit-img" src="{{ url_for('static', filename='uploads/default.jpeg') }}" alt="Default benefit image">
			{% endif %}
                    </div>
                    <h5>Description</h5>
		    <div class="benefit-description text-start">
                    	{{ benefit.description | nl2br | safe }}
		    </div><br>
                    <h5>Requirement</h5>
                    <div class="benefit-requirement text-start">
                        {{ benefit.benefit_requirement | nl2br | safe }}
                    </div><br>
                    <div class="">
                        {% if benefit.benefit_created_by %}
                          <a class="mb-3" href="{{ url_for('benefits.user_benefits', username=benefit.benefit_created_by) }}">Post By {{ benefit.benefit_created_by }}</a> On {{ benefit.benefit_created_on.strftime('%Y-%m-%d') }}<br>
                        {% else %}
                          <span class="mb-3">Post By: Unable to display user</span>
                        {% endif %}
                        <small class="text-muted">
                            Start Date: {{ benefit.benefit_start_date.strftime('%Y-%m-%d') }}<br>
                            End Date: {{ benefit.benefit_end_date.strftime('%Y-%m-%d') }}
                        </small>
                    </div>
                    <button data-link="{{ benefit.benefit_link }}" class="btn btn-primary apply-button">Apply</button>
                </div>
            </div>
        {% endfor %}
    </div>
    {% for page_num in benefits.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if benefits.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('benefits.explore_benefits', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('benefits.explore_benefits', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

benefitsHub/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <!-- Intro Section -->
    <section id="intro" class="intro-section">
	<div class="slideshow-container">
	     <div class="slide fade">
		<img class="banner" src="{{ url_for('static', filename='/assets/cover-images/cover-image_1.jpeg') }}" alt="Cover Image">
	     </div>
	     <div class="slide fade">
		<img class="banner" src="{{ url_for('static', filename='/assets/cover-images/cover-image_2.jpeg') }}" alt="Cover Image"> 
	     </div>
	     <div class="slide fade">
		<img class="banner" src="{{ url_for('static', filename='/assets/cover-images/cover-image_3.jpeg') }}" alt="Cover Image"> 
	     </div>
	     <div class="slide fade">
		<img class="banner" src="{{ url_for('static', filename='/assets/cover-images/cover-image_4.jpeg') }}" alt="Cover Image"> 
	     </div>
	    <div class="slide fade">
		<img class="banner" src="{{ url_for('static', filename='/assets/cover-images/cover-image_5.jpeg') }}" alt="Cover Image">
	    </div>
        </div>
    </section>

    <div class="intro-div">
            <h1 class="text-success">BenefitsHub Nigeria</h1>
            <h6>Your one-stop hub for government benefits in Nigeria.</h6>
            <a href="{{ url_for('benefits.explore_benefits') }}" class="btn-primary">Explore Benefits</a>
    </div>

   <!-- Feature Section -->
    <section id="features" class="row features">
        <h2>Key Features</h2>
        <div class="image-container">
            <!-- Feature 1 -->
            <div class="feature">
                <img class="feature-img" src="{{ url_for('static', filename='assets/img_0.jpeg') }}" alt="Feature 1">
                <h3>Real-time Updates About Benefits You Can Apply To</h3>
                <p class="text-start">
                    Stay updated with real-time notifications on newly posted benefits from various government schemes. No need to miss out on the action, just come here and find everything you need!
                </p>
                <a href="{{ url_for('benefits.explore_benefits') }}">See Updates</a>
            </div>
            <!-- Feature 2 -->
            <div class="feature">
                <img class="feature-img" src="{{ url_for('static', filename='assets/cover-images/cover-image_8.jpeg') }}" alt="Feature 2">
                <h3>Search Benefits by Category</h3>
                <p class="text-start">Easily search and filter benefits by categories such as education, healthcare, employment, and more. Seamlessly apply for benefits online through our platform with step-by-step guidance.</p>
                <a href="{{ url_for('benefits.explore_benefits') }}">Explore Here</a>
            </div>
            <!-- Feature 3 -->
            <div class="feature">
                <img class="feature-img" src="{{ url_for('static', filename='assets/img_2.jpeg') }}" alt="Feature 3">
                <h3>Share Your Thoughts By Making Blog</h3>
                <p class="text-start">Create an account and blog your thoughts about government schemes and programs. Share tips and any other useful information.</p>
                <a href="{{ url_for('posts.new_post') }}">Make A Post</a>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section id="about" class="about-section">
        <h2>About BenefitsHub Nigeria</h2>
        <p class="text-start">
            The inspiration for <b>BenefitsHub Nigeria</b> came from the lack of centralized information about government benefits. It is a website where you can explore and apply for all current benefits offered by goverment agencies in Nigeria. As you know, Information is crucial if you must become aware of government programs that you may benefit from, as of now, there is no single website that provides a well-curated list of available government benefits. <b>BenefitsHub</b> seeks to fill that vacuum by curating all government schemes and programs that are meant to assist citizens, especially unemployed citizens. It is your one-stop shop for everything empowerment, grants, low-interest loans and a wide range of other benefits offered by the government. We update you with all programs of government that are aimed as a palliative to cushion the effect of the global economic downturn.  Do not lose out on any government intervention because you missed the information. Simply create an account and login to apply and track the status of your application.
        </p>
        <p class="text-start">
            Our mission is to help Nigerians access available government benefits more easily and efficiently.
            This project was developed as a <a class="no-hover" href="https://github.com/JuliusDgenius/alx-portfolio_project">Portfolio Project</a> for <a class="no-hover" href="https://www.alxafrica.com/">alx Africa.</a>
        </p>
        <div class="team">
            <h3>Meet the Team</h3>
            <ul>
                <li>
                    <h4>Julius Ibe - Fullstack.</h4>
                    <p>
                        <a target="_blank" href="https://www.linkedin.com/in/julius-ibe">LinkedIn</a> |
                        <a target="_blank" href="https://github.com/JuliusDgenius">GitHub</a> |
                        <a target="_blank" href="https://twitter.com/0xjulius_">Twitter</a>
                    </p>
                </li>
                <!-- Add more team members here -->
            </ul>
        </div>
        <a target="_blank" href="https://github.com/JuliusDgenius/alx-portfolio_project" class="btn-primary">View GitHub Repository</a>
    </section>

    <!-- Optional Video Section -->
    <!-- <section id="video" class="video-section">
        <h2>Our Journey</h2>
        <video controls>
            <source src="{{ url_for('static', filename='assets/project_intro.mp4') }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </section> -->
{% endblock content %}

benefitsHub/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author) }}">{{ post.author }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user.username %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <div>
	{% if post.post_image %}
    		<img class="img-fluid benefit-img" src="{{ url_for('static', filename='uploads/' + post.post_image) }}" alt="Post picture">
	{% else %}
    		<img class="img-fluid benefit-img" src="{{ url_for('static', filename='uploads/default.jpeg') }}" alt="Default post image">
	{% endif %}
      </div>
      <h2 class="article-title text-start">{{ post.title }}</h2>
      <div class="article-content text-start">{{ post.content | nl2br | safe }}</div>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}